archive/urls.py
# -*- coding: utf-8 -*-
#
# urls.py for app 'page'
#

from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy

from archive.views import ArchiveView


urlpatterns = patterns('',
    # notice list view
    url(r'^all$', ArchiveView.as_view(),
        name='archive_all'),
    url(r'^archive/all$',
        RedirectView.as_view(url=reverse_lazy('archive_all'))),
)

django_skaschool/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView

from page.views import IndexView


urlpatterns = patterns('',
    # admin
    url(r'^admin/', include(admin.site.urls)),
    # index page
    url(r'^$', IndexView.as_view(), name='index'),
    # app 'page'
    url(r'^page/', include('page.urls')),
    # app 'schedule'
    url(r'^schedule/', include('schedule.urls')),
    # app 'notice'
    url(r'^notice/', include('notice.urls')),
    # app 'archive'
    url(r'^archive/', include('archive.urls')),
)

## django-registration
urlpatterns += patterns('',
    # url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('account.urls')),
)


## staticfiles
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page/urls.py
# -*- coding: utf-8 -*-
#
# urls.py for app 'page'
#

from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView, RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = patterns('',
    # index page
    url(r'^$', RedirectView.as_view(url=reverse_lazy('index'))),
    # introduction page
    url(r'^introduction/$',
        TemplateView.as_view(template_name='page/introduction.html'),
        name='introduction'),
    # committee page
    url(r'^committee/$',
        TemplateView.as_view(template_name='page/committee.html'),
        name='committee'),
    # sponsor page
    url(r'^sponsor/$',
        TemplateView.as_view(template_name='page/sponsor.html'),
        name='sponsor'),
    # traffic page
    url(r'^traffic/$',
        TemplateView.as_view(template_name='page/traffic.html'),
        name='traffic'),
    # accommodation page
    url(r'^accommodation/$',
        TemplateView.as_view(template_name='page/accommodation.html'),
        name='accommodation'),
    # contact page
    url(r'^contact/$',
        TemplateView.as_view(template_name='page/contact.html'),
        name='contact'),
    # about page
    url(r'^about/$',
        TemplateView.as_view(template_name='page/about.html'),
        name='about'),
)

archive/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.db.models.signals import pre_delete
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from tools.storage import OverwriteStorage, file_cleanup


class Archive(models.Model):
    """
    model 'Archive' to record uploaded files and provide downloads
    """
    title = models.CharField(_("Title"), max_length=100)
    pubtime = models.DateTimeField(_("Publish time"), auto_now_add=True)
    category = models.ForeignKey('ArchiveCategory', verbose_name=_("Category"))
    publisher = models.ForeignKey(User, verbose_name=_("Publisher"))
    description = models.TextField(_("Description"))
    file = models.FileField(verbose_name=_("File"),
            upload_to=lambda instance, filename: u'archive/cat{0}/{1}'.format(instance.category.id, filename),
            storage=OverwriteStorage())

    class Meta:
        verbose_name = _('archive')
        verbose_name_plural = _('archives')
        ordering = ['category', '-pubtime', 'id']

    def __unicode__(self):
        return u'Archive #%s: (%s) %s' % (
                self.id, self.category.name, self.title)

    def show_pubtime(self):
        # used in 'list_notice.html' template
        return self.pubtime.strftime('%Y-%m-%d')

    def save(self, *args, **kwargs):
        """
        overwrite the original save method to delete old file
        """
        if not self.pk:
            # -> create
            return super(type(self), self).save(*args, **kwargs)
        # already exists -> edit
        old_obj = type(self).objects.get(pk=self.pk)
        result = super(type(self), self).save(*args, **kwargs)
        # if the path is the same, the file is overwritten already
        if old_obj.file.name:
            # old_obj has file
            if not self.file.name:
                # new object has no file
                old_obj.file.delete(save=False)
            elif old_obj.file.path != self.file.path:
                # new object has file, and differ from old_obj
                old_obj.file.delete(save=False)
        #
        return result


class ArchiveCategory(models.Model):
    """
    model 'NoticeCategory' to provide category selections for 'Notice'
    """
    name = models.CharField(_("Category name"), max_length=100)
    created_at = models.DateTimeField(_("Created time"), auto_now_add=True)

    class Meta:
        verbose_name = _('archive category')
        verbose_name_plural = _('archive categories')

    def __unicode__(self):
        return u'ArchiveCategory: %s' % self.name


### connect to signal and sender
pre_delete.connect(file_cleanup, sender=Archive)

archive/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.views.generic.base import TemplateView

from archive.models import Archive, ArchiveCategory


class ArchiveView(TemplateView):
    """
    class-based view to show archives
    """
    template_name = 'archive/archive.html'

    def get_context_data(self, **kwargs):
        """
        add 'user' context
        """
        context = super(type(self), self).get_context_data(**kwargs)
        archive_categories = ArchiveCategory.objects.all()
        if Archive.objects.all():
            archive_empty = False
        else:
            archive_empty = True
        context['archive_categories'] = archive_categories
        context['archive_empty'] = archive_empty
        return context

archive/templates/archive/archive.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load url from future %}
{% load i18n %}
{% load bootstrap3 %}

{# template to show notice list #}

{% block pagetitle %}资料下载{% endblock %}

{% block css_extra %}
  <link href="{% static 'css/sidebar.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="container">
    <h2>资料下载</h2>
    <hr>
  </div>

  <div class="container">
    {% if archive_empty %}
    <div class="alert alert-info">
      暂无资料提供下载……
    </div>
    {% else %}
    <div class="row">
    <div class="col-md-10" id="content-col">
    {# archive contents #}
    {% for category in archive_categories %}
      <h3 id="cat{{ category.id }}">{{ category.name }}</h3>
      <table class="table table-stripped table-bordered table-hover">
      {% with archives=category.archive_set.all %}
      {% for archive in archives %}
      <tr>
        <th class="col-md-3"><a href="{{ archive.file.url }}">{{ archive.title }}</a></th>
        <td class="col-md-7">{{ archive.description }}</td>
      </tr>
      {% empty %}
      <tr class="warning">
        <td>暂无该类资料可供下载</td>
      </tr>
      {% endfor %}
      {% endwith %}
      </table>
    {% endfor %}
    </div>
    <div class="col-md-2" id="sidebar-col">
    {# archive sidebar #}
    <ul class="nav nav-stacked" id="sidebar">
    {% for category in archive_categories %}
      <li><a href="#cat{{ category.id }}">{{ category.name }}</a></li>
    {% endfor %}
    </ul>
    </div>
    </div>
    {% endif %}
  </div>
{% endblock %}

{% block js_extra %}
  <script src="{% static 'js/sidebar.js' %}" type="text/javascript"></script>
{% endblock %}

{# vim: set ts=8 sw=2 tw=0 fenc=utf-8 ft=htmldjango.html: #}